### ISSUE TITLE
PHP env. checker rewrite

### ISSUE THREAD

**Issue by szepeviktor** [decodelabs/systemic#1]
Could it be that it is possible to rewrite my one-file [PHP env. checker](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/php-env-check.php) (used in production) in systemic?

**Comment by betterthanclay** [comment]
Hi Viktor.

This could definitely be a feature to add to Systemic, though it would almost definitely be more than a single-file script; the idea of the Systemic library is to offer easy access to system information in various contexts in a granular fashion, and there's a lot going on in your env checker.

I think the best thing would be for me to try to break down all of the different pieces of information you're working with in the env checker script and ensure that each of them are covered in some way in Systemic via plugins, then once all of that is in place I can have a look at creating a separate script file (that could go in composer's bin dir) that pulls all of those separate things together into one checker script similar to your current iteration.

I've added it to my todo list, though it will likely take a while :)

**Comment by szepeviktor** [comment]
It has two purposes

1. Document the environment
1. And check it

It has assertions for

1. enabled PHP extensions
1. disabled PHP extensions
1. PHP directive values
1. enabled PHP functions
1. version numbers
1. directories whether they are writable

**Comment by szepeviktor** [comment]
I can barely convince devs and project owners to include it. I think a complete package may not get an easy approval for inclusion.

**Comment by betterthanclay** [comment]
Hi Viktor.

I know this is from a long time ago - essentially this sort of feature should be its own standalone package and not something I'm looking to add directly to Systemic. It could be implemented _using_ this library though!
